# Generated by Django 4.1.6 on 2023-02-15 13:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
