# Generated by Django 4.1.6 on 2023-02-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portfolio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
