# Generated by Django 4.1.6 on 2023-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='portfolio',
            field=models.CharField(blank=True, choices=[('Household RO', 'Household RO'), ('Electric Appliances', 'Electric Appliances'), ('Commercial RO', 'Commercial RO'), ('Construction/Sanitary', 'Construction/Sanitary'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('GCC', 'GCC'), ('MEA', 'MEA'), ('SA', 'SA'), ('SEA', 'SEA'), ('America', 'America'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('East Asia', 'East Asia'), ('Australia', 'Australia')], default='GCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('Alibaba', 'Alibaba'), ('WATI', 'WATI'), ('Google', 'Google'), ('Trade Fairs', 'Trade Fairs'), ('Custom Data', 'Custom Data'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
