# Generated by Django 4.1.6 on 2023-02-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('', 'Choose Category'), ('RO standard', 'RO standard'), ('RO Cabinet', 'RO Cabinet'), ('Dispenser', 'Dispenser'), ('RO commercial', 'RO commercial'), ('Air industry', 'Air industry'), ('Accessories', 'Accessories'), ('Air industry', 'Air industry'), ('Pet filter', 'Pet filter'), ('Other', 'Other')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_type', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('qty_per_ctn', models.IntegerField(blank=True, default=1, null=True)),
                ('ctn_length', models.IntegerField(blank=True, default=300, null=True)),
                ('ctn_width', models.IntegerField(blank=True, default=300, null=True)),
                ('ctn_heigh', models.IntegerField(blank=True, default=300, null=True)),
                ('status', models.CharField(choices=[('', 'Choose product status'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Canceled', 'Canceled')], default='Active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='haict', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productgroup')),
            ],
            options={
                'ordering': ('product_code',),
            },
        ),
    ]
