# Generated by Django 4.1.6 on 2023-02-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='category',
            new_name='group',
        ),
    ]
