# Generated by Django 4.1.6 on 2023-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_productgroup_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('group',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ctn_heigh',
            new_name='ctn_height',
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
