# Generated by Django 4.1.6 on 2023-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RO standard', 'RO standard'), ('RO Cabinet', 'RO Cabinet'), ('Dispenser', 'Dispenser'), ('RO commercial', 'RO commercial'), ('Air industry', 'Air industry'), ('Accessories', 'Accessories'), ('Air industry', 'Air industry'), ('Pet filter', 'Pet filter'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Canceled', 'Canceled')], default='Active', max_length=24),
        ),
    ]
