# Generated by Django 4.1.6 on 2023-02-27 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_assign_alter_task_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_per',
            field=models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
