# Generated by Django 4.1.6 on 2023-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_task_complete_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working', 'Working'), ('Done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('On Due', 'On Due'), ('Overdue', 'Overdue'), ('Done', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working', 'Working'), ('Done', 'Done')], default=1, max_length=7),
        ),
    ]
