# Generated by Django 4.1.6 on 2023-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_status_alter_task_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dead_line',
            field=models.DateField(blank=True, null=True),
        ),
    ]
