# Generated by Django 4.1.6 on 2023-03-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_remove_project_assign_project_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign',
        ),
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
