# Generated by Django 4.1.6 on 2023-03-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_task_assign_task_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='efforts',
        ),
    ]
