# Generated by Django 4.1.6 on 2023-03-09 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_efforts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='complete_per',
            field=models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working', 'Working'), ('Done', 'Done')], default='Working', max_length=7),
        ),
    ]
