# Generated by Django 4.1.6 on 2023-02-15 01:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('', 'Choose Priority'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('', 'Choose lead status'), ('1.follow-up', '1.follow-up'), ('2.demanded', '2.demanded'), ('3.offered', '3.offered'), ('4.dealing', '4.dealing'), ('5.ordered', '5.ordered'), ('6.lost', '6.lost')], default='2.demanded', max_length=14),
        ),
    ]
