# Generated by Django 4.1.6 on 2023-02-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_country_alter_lead_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='portfolio',
            field=models.CharField(blank=True, choices=[('', 'Choose Portfolio'), ('Household RO', 'Household RO'), ('Electric Appliances', 'Electric Appliances'), ('Commercial RO', 'Commercial RO'), ('Construction/Sanitary', 'Construction/Sanitary'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Choose Source'), ('Alibaba', 'Alibaba'), ('WATI', 'WATI'), ('Google', 'Google'), ('Trade Fairs', 'Trade Fairs'), ('Custom Data', 'Custom Data')], max_length=50, null=True),
        ),
    ]
