# Generated by Django 4.1.6 on 2023-02-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_portfolio_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Choose Source'), ('Alibaba', 'Alibaba'), ('WATI', 'WATI'), ('Google', 'Google'), ('Trade Fairs', 'Trade Fairs'), ('Custom Data', 'Custom Data'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
