# Generated by Django 4.1.6 on 2023-02-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(choices=[('', 'Choose Region'), ('GCC', 'GCC'), ('MEA', 'MEA'), ('SA', 'SA'), ('SEA', 'SEA'), ('America', 'America'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('East Asia', 'East Asia'), ('Australia', 'Australia')], default='GCC', max_length=10),
        ),
    ]
