# Generated by Django 4.1.6 on 2023-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='care_update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
