# Generated by Django 4.1.6 on 2023-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_lead_care_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
