# Generated by Django 4.1.6 on 2023-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_lead_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='portfolio',
            field=models.CharField(blank=True, choices=[('Household RO', 'Household RO'), ('Electric Appliances', 'Electric Appliances'), ('Commercial RO', 'Commercial RO'), ('Construction/Sanitary', 'Construction/Sanitary'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='region',
            field=models.CharField(choices=[('GCC', 'GCC'), ('MEA', 'MEA'), ('SA', 'SA'), ('SEA', 'SEA'), ('America', 'America'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('East Asia', 'East Asia'), ('Australia', 'Australia')], default='GCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Alibaba', 'Alibaba'), ('WATI', 'WATI'), ('Google', 'Google'), ('Trade Fairs', 'Trade Fairs'), ('Custom Data', 'Custom Data'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('1.follow-up', '1.follow-up'), ('2.demanded', '2.demanded'), ('3.offered', '3.offered'), ('4.dealing', '4.dealing'), ('5.ordered', '5.ordered'), ('6.lost', '6.lost')], default='2.demanded', max_length=14),
        ),
    ]
