# Generated by Django 4.1.6 on 2023-02-16 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('client', '0006_client_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_productmodel_alter_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('load_date', models.DateField(blank=True, null=True)),
                ('etd_date', models.DateField(blank=True, null=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('deposit', models.FloatField(default=0)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('payment1', models.FloatField(default=0)),
                ('payment1_date', models.DateField(blank=True, null=True)),
                ('payment2', models.FloatField(default=0)),
                ('payment2_date', models.DateField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('freight', models.FloatField(default=0)),
                ('booking', models.CharField(max_length=30)),
                ('ship_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('trucking_fee', models.IntegerField(default=0)),
                ('local_charge', models.IntegerField(default=0)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('declaration', models.CharField(blank=True, max_length=30, null=True)),
                ('declare_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', 'Choose Status'), ('drafted', 'drafted'), ('opened', 'opened'), ('shipped', 'shipped'), ('closed', 'closed'), ('on hold', 'on hold')], default='drafted', max_length=14)),
                ('client', models.ForeignKey(default='Example Company', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='client.client')),
                ('pic', models.ForeignKey(default='haict', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='ShipLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=20)),
                ('note', models.TextField()),
            ],
            options={
                'ordering': ('line_name',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('item_status', models.CharField(choices=[('', 'Choose item status'), ('Confirmed', 'Confirmed'), ('Temporary', 'Temporary'), ('SXXK', 'SXXK')], default='Temporary', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='haict', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orderdetails', to=settings.AUTH_USER_MODEL)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='order.order')),
                ('product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdetails', to='product.product')),
            ],
            options={
                'ordering': ('product_code',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ship_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.shiplines'),
        ),
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='team.team'),
        ),
    ]
