# Generated by Django 4.1.6 on 2023-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shiplines_tracking_link_alter_shiplines_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
