# Generated by Django 4.1.6 on 2023-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='FOC',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='item_cbm',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
