# Generated by Django 4.1.6 on 2023-02-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderdetail_foc_orderdetail_item_cbm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='item_cbm',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
