# Generated by Django 4.1.6 on 2023-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderdetail_item_cbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='item_cbm',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
