# Generated by Django 4.1.6 on 2023-02-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderdetail_item_cbm_orderdetail_item_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='item_cbm',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
