# Generated by Django 4.1.6 on 2023-02-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderdetail_item_cbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='FOC',
            field=models.BooleanField(default=False),
        ),
    ]
