# Generated by Django 4.1.6 on 2023-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderdetail_foc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shiplines',
            name='line_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
