# Generated by Django 4.1.6 on 2023-02-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_number_alter_shiplines_line_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFile',
        ),
    ]
